layout{
    size: 3in, 3in
    dpi: 300
}

export {
    tts {
        size: 2, 2
    }
}

string{
    type: text
    font-family: Verdana
    width: 3in
    height: 3in
    text: hi there \< foo bar
    align: left, top
    font-size: 44pt
}

line_quarterin {
    type: line
    line-color: orchid
    #y: 1/8in
    x: .25in
    x2: .25in
    y2: .25in
}

line_38 {
    type: line
    line-color: deepskyblue
    x: 3/8in
    x2: 3/8in
    y2: 3/8in
}

line_halfin {
    type: line
    line-color: orange
    x: .5in
    x2: .5in
    y2: .5in
}

line_3quarterin {
    type: line
    line-color: red
    x: 3/4in
    x2: 3/4in
    y2: 3/4in
}

line_1in {
    type: line
    x: 1in
    x2: 1in
    y2: 1in
}
