layout{
    size: 2in, 2in
    dpi: 300
}

export {
    tts {
        size: 2, 2
    }
}

defaults {
    align: left, top
    size: 1in, 1in

}

box {
    type: rect
    size: 1in, 1in
}

string {
    type: text
    font-family: Verdana
    size: 1in, 1in
    font-size: 12pt
    shrink-font: 20: 5pt
    align: left, top
    #text: card layout
    text: this is a long piece of text, I wonder how long it can be????
}



